version: '3'
services:
  database:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - db-volume-sample:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: sample

volumes:
  db-volume-sample:
